version: '2'
services:
  node:
    container_name: mqtt-echoback
    build:
      context: '.'
    volumes:
      - ".:/app:cached"
      - "/app/node_modules"
    working_dir: "/app"
    command: "npm start"
